# Generated by Django 4.0.7 on 2022-09-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentapiStudentinfo',
            fields=[
                ('studentname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='StudentName', max_length=100)),
                ('studentrollno', models.IntegerField(db_column='StudentRollNo', primary_key=True, serialize=False)),
                ('studentbranch', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='StudentBranch', max_length=3)),
                ('studentgpa', models.FloatField(db_column='StudentGPA')),
                ('studentsection', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='StudentSection', max_length=1)),
            ],
            options={
                'db_table': 'StudentApi_studentinfo',
                'managed': False,
            },
        ),
    ]
